---

- name: Install the cgroup packages (Redhat)
  yum:
    name:
      - libcgroup
      - libcgroup-tools
    state: present
  when: ansible_os_family == "Redhat"

- name: Install the cgroup packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - libcgroup1
      - cgroup-tools
    state: present
    cache_valid_time: 600
  when: ansible_os_family == "Debian"

- name: Enable and start cgroup services
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - cgred
    - cgconfig
  changed_when: false  # workaround so idempotence CI tests work in docker

- name: Copy CGROUPS /etc/cgconfig.conf to limit memory usage
  template:
    src: cgconfig.conf.j2
    dest: /etc/cgconfig.conf
    owner: root
    mode: 0644
  notify: restart cgconfig

- name: Copy CGROUPS /etc/cgrules.conf to limit memory usage
  template:
    src: cgrules.conf.j2
    dest: /etc/cgrules.conf
    owner: root
    mode: 0644
  notify: restart cgred
